dependencies:
  flutter:
    sdk: flutter
  firebase_core: latest_version
  firebase_auth: latest_version
  cloud_firestore: latest_version
  flutter_bloc: latest_version
  bloc: latest_version
  provider: latest_version
  intl: latest_version
  cupertino_icons: latest_version
